#!/usr/bin/env python

from zensols.cli import ConfigurationImporterCliHarness

if (__name__ == '__main__'):
    harness = ConfigurationImporterCliHarness(
        src_dir_name='src/python',
        app_factory_class='zensols.showfile.ApplicationFactory',
        proto_args='show -W 1000 -H 1000 h://example.com',
        proto_factory_kwargs={'reload_pattern': r'^zensols.showfile'},
    )
    harness.run()
